### ISSUE TITLE
README instructions to run

### ISSUE THREAD

**Issue by gcgrossi** [guptarohit/cryptoCMD#2]
Hi! I am trying to use the code following the instructions in the README. I installed the package and created a python file run.py with the following commands

from cryptocmd import CmcScraper                              
scraper = CmcScraper('XRP')
scraper.export_csv('xrp_all_time.csv')

and run it with 
python run.py

I get the following errors from python
Traceback (most recent call last):
  File "scrape_test.py", line 1, in <module>
    from cryptocmd import CmcScraper
  File "/home/ggrossi/cryptoCMD/cryptocmd/__init__.py", line 1, in <module>
    from .core import *
  File "/home/ggrossi/cryptoCMD/cryptocmd/core.py", line 84
    print(*self.headers, sep=', ')
          ^
SyntaxError: invalid syntax

I don't know if it's my issue but maybe some more detailed instructions would be nice. Thank you

**Comment by guptarohit** [comment]
Hi :hand: 
Your code is fine.
Are you using python 2? This error maybe because of that.
This package currently support python 3.
Soon I'll make a patch to support python 2 as well :v:

**Comment by gcgrossi** [comment]
Yes I also think it is because python2. I will try with 3. Thank you!

Giulio Cornelio Grossi, PhD

--------------------------------------------------------
Research
Quantitative and Big Data Analysis
Mathematical Modeling
-------------------------------------------------------

Il 04/feb/2018 17:28, "Rohit Gupta" <notifications@github.com> ha scritto:
