### ISSUE TITLE
New Issue - list index out of range

### ISSUE THREAD

**Issue by SarchB** [guptarohit/cryptoCMD#34]
**This is a(n):**
- [x] Error

**Details:**
On https://pypi.org/project/cryptocmd/ the example use is:

```
from cryptocmd import CmcScraper

# initialise scraper with time interval
scraper = CmcScraper("XRP", "15-10-2017", "25-10-2017")

# get raw data as list of list
headers, data = scraper.get_data()

# get data in a json format
json_data = scraper.get_data("json")

# export the data to csv
scraper.export("csv")

# get dataframe for the data
df = scraper.get_dataframe()
```

This used to work perfect when I ran it a couple of days ago. However now it keeps returning:

```
>>> from cryptocmd import CmcScraper
>>> scraper = CmcScraper("XRP", "15-10-2017", "25-10-2017")
>>> headers, data = scraper.get_data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$USER/.local/lib/python3.8/site-packages/cryptocmd/core.py", line 97, in get_data
    self._download_data(**kwargs)
  File "/home/$USER/.local/lib/python3.8/site-packages/cryptocmd/core.py", line 83, in _download_data
    self.end_date, self.start_date, self.headers, self.rows = extract_data(table)
  File "/home/$USER/.local/lib/python3.8/site-packages/cryptocmd/utils.py", line 161, in extract_data
    end_date, start_date = rows[0][0], rows[-1][0]
IndexError: list index out of range

```

I tried different currencies and dates. All give the same error. 

Could it be coinmarketcap changed their HTML layout? I tried fixing the issue myself but my knoowledge of PyQuery is limited and I couldn't figure it out. that    ` headers = [col.text_content().strip("*") for col in raw_data("table:first>thead>tr>th")]` is now returning empty strings.

**Comment by Adrok24** [comment]
It gives me the same error!

**Comment by jamzrob** [comment]
same error

**Comment by nchos88** [comment]
same here.

**Comment by SarchB** [comment]
Fixed it, made a git command via my cli. All seemed to work fine but the commit isn't showing up. 

Just copy the following function in utils.py on line 10

```
from selenium import webdriver

def start_browser(url):
    """
    This method retrieves the HTML source code from a dynamically loaded webpage.
    :param url: 'url' of the web page to download
    :return: HTML source code formatted as a string
    """
    try:
        options = webdriver.ChromeOptions()
        options.add_argument('headless')
        options.add_argument('window-size=1920x1080')
        options.add_argument("disable-gpu")
        browser = webdriver.Chrome(chrome_options=options)
    except:
        options = Options()
        options.add_argument('--headless')
        browser = webdriver.Firefox(options=options)
    browser.get(url)
    return browser.page_source
```

And then change the first try statement in the get_url_data function to:

```
try:
        response = start_browser(url)
        return response
```

Finally, change the following line (which appears twice in utils.py):

`html = get_url_data(url).text`

into:

`html = get_url_data(url)
`

Problem was that coinmarketcap now uses Javascript to show the historical data table. So we can only grab the needed HTML sourcecode once it is loaded into a browser. Selenium is used for this purpose. Not sure if this setup will work for all, and the repositories maintainer might like some more changed to proberly embed the change, yet it should help get you going..

**Comment by SarchB** [comment]
Ah, one more error popped up. 

It  appears that https://coinmarketcap.com/all/views/all/ which is used to translate the coincode to a coinname now no longer displays all currencies. It only displays the first 200 coins, then it requires you to click 'show more' to show the others. 

Will see if I can get python and selenium to similate that click.

**Comment by SarchB** [comment]
Ok, managed to solve it for my own user case. Code however is ugly and very un-uptimized, use at own risk:

```
def start_browser(url, trigger=None):
    """
    This method retrieves the HTML source code from a dynamically loaded webpage.
    :param url: 'url' of the web page to download
    :return: HTML source code formatted as a string
    """
    try:
        options = webdriver.ChromeOptions()
        options.add_argument('headless')
        options.add_argument('window-size=1920x1080')
        options.add_argument("disable-gpu")
        options.add_experimental_option("prefs", {"profile.default_content_settings.cookies": 2})
        browser = webdriver.Chrome(chrome_options=options)
    except:
        options = webdriver.FirefoxOptions()
        options.add_argument('--headless')
        browser = webdriver.Firefox(options=options)
    browser.get(url)

    if url == "http://coinmarketcap.com/all/views/all/" and trigger == 1:
        last_height = browser.execute_script("return document.body.scrollHeight")
        browser.execute_script("window.scrollTo(0, 8900);")
        element = browser.find_element_by_xpath("*//button[text()='Load More']")
        ActionChains(browser).click(element).perform()
        SCROLL_PAUSE_TIME = 0.5
        base = 8900
        while True:
            base += 200
            browser.execute_script(f"window.scrollTo(0, {base});")
            time.sleep(SCROLL_PAUSE_TIME)
            new_height = browser.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height

    return browser.page_source

def get_url_data(url):
    """
    This method downloads the data of the web page.
    :param url: 'url' of the web page to download
    :return: response object of get request of the 'url'
    """

    if url == "http://coinmarketcap.com/all/views/all/":
        response = get(url)
        return response

    try:
        response = start_browser(url)
        return response
    except Exception as e:
        if hasattr(e, "message"):
            print("Error message (get_url_data) :", e.message)
        else:
            print("Error message (get_url_data) :", e)
        raise e

def get_coin_id(coin_code):
    """
    This method fetches the name(id) of currency from the given code
    :param coin_code: coin code of a cryptocurrency e.g. btc
    :return: coin-id for the a cryptocurrency on the coinmarketcap.com
    """

    try:
        url = "http://coinmarketcap.com/all/views/all/"

        html =  get_url_data(url).text
        raw_data = pq(html)

        coin_code = coin_code.upper()
        data_table = raw_data("tbody")[0]

        for _row in data_table.findall("tr"):
            symbol = _row.findall("td")[2].text_content()
            coin_link = _row.findall("td")[1].find_class("cmc-link")[0]
            coin_id = coin_link.values()[0].replace("/currencies/","")[:-1]
            if symbol == coin_code:
                return coin_id

        html =  start_browser(url, 1)
        raw_data = pq(html)

        coin_code = coin_code.upper()
        data_table = raw_data("tbody")[0]

        for _row in data_table.findall("tr"):
            symbol = _row.findall("td")[2].text_content()
            coin_link = _row.findall("td")[1].find_class("cmc-link")[0]
            coin_id = coin_link.values()[0].replace("/currencies/","")[:-1]
            if symbol == coin_code:
                return coin_id

        raise InvalidCoinCode("'{}' coin code is unavailable on coinmarketcap.com".format(coin_code))
    except Exception as e:
        raise e
```

**Comment by guptarohit** [comment]
Thanks for raising the issue, fixed in new release :tada: please update.
